version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: file-type
    versions:
    - 16.2.0
  - dependency-name: connect-redis
    versions:
    - 5.0.0
    - 5.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: ejs
    versions:
    - 3.1.5
