version: "3.2"
services:
    si_app:
        build:
            context: .
            args:
                - NODE_ENV=development
        volumes:
            -  .:/usr/src/simpleimage
            -  node_modules:/usr/src/simpleimage/node_modules
        command: bash -c "npm run build:client & npm run start:dev"
        environment:
            - NODE_ENV=development

volumes:
    node_modules: