version: "3.2"
services:
    si_app:
        build:
            context: .
            args:
                - NODE_ENV=development
        volumes:
            -  .:/usr/src/simpleimage
            -  node_modules:/usr/src/simpleimage/node_modules
        command: bash -c "npm run watch:client & npm run start:dev"
        environment:
            - NODE_ENV=development
        ports:
            - "8081:3011"
    si_sessions:
        ports:
            - "6379:6379"
    dozzle:
        container_name: si-dozzle
        image: amir20/dozzle:latest
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        ports:
        - 9999:8080

volumes:
    node_modules: