version: "3.2"
services:
    si_app:
        build:
            args:
                - NODE_ENV=production
        command: bash -c "npm run start:test"
        environment:
            - NODE_ENV=production
