version: "3.2"
services:
    si_app:
        build:
            context: .
            args:
                - NODE_ENV=production
        image: coteh/simpleimage
        container_name: si-app
        command: bash -c "npm run build:client && npm start"
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        ports:
            - "8080:3010"
        depends_on:
            - "si_db"
    si_db:
        image: mongo:3.6.4
        container_name: si-db
        ports:
            - "27017:27017"
        volumes:
            -   type: volume
                source: configdb
                target: /data/configdb
                volume:
                    nocopy: true
            -   type: volume
                source: db
                target: /data/db
                volume:
                    nocopy: true
            -   type: bind
                source: ./mongo-entrypoint
                target: /docker-entrypoint-initdb.d
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITIAL_DATABASE}
    si_sessions:
        image: redis:4.0.6
        container_name: si-sessions
        ports:
            - "6379:6379"

volumes:
    configdb:
    db: