version: 2.1
jobs:
  build-and-test:
    docker:
      - image: coteh/si-test-deps:0.0.2
    steps:
      - checkout
      - restore_cache:
          key: v2-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: v2-{{ checksum "package-lock.json" }}
          paths:
            - "$HOME/.npm"
      - run:
          name: Run tests
          command: npm run test-ci
          environment:
              MOCHA_FILE: ./junit/simpleimage/test-results.xml
      - store_test_results:
          path: ./junit
workflows:
    build-and-test:
      jobs:
        - build-and-test