version: 2.1
orbs:
    codecov: codecov/codecov@1.0.5
    # cypress: cypress-io/cypress@1
jobs:
  run-integ-tests:
    docker:
      - image: coteh/si-test-deps:0.0.2
    steps:
      - checkout
      - restore_cache:
          key: v3-{{ checksum "package-lock.json" }}
      - run:
          name: npm maybe-install
          command: if [ ! -d "node_modules" ]; then npm ci; fi
      - save_cache:
          key: v3-{{ checksum "package-lock.json" }}
          paths:
            - "$HOME/.npm"
            - "node_modules"
      - run:
          name: Run tests
          command: npm run test-ci
          environment:
              MOCHA_FILE: ./junit/simpleimage/test-results.xml
      - codecov/upload:
          file: ./coverage/lcov.info
      - store_artifacts:
          path: ./coverage
      - store_test_results:
          path: ./junit
  # run-cypress-tests: TODO add Cypress to CircleCI pipeline
workflows:
    build-and-test:
      jobs:
        - run-integ-tests
        # - run-cypress-tests
