version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: apt-get install -y exiftran
            - run: npm install
            - run:
                name: Run tests
                command: mocha test --reporter mocha-junit-reporter
                environment:
                    NODE_ENV: test
                    MOCHA_FILE: ./junit/simpleimage/test-results.xml
            - store_test_results:
                path: ./junit
workflows:
    build-and-test:
      jobs:
        - build-and-test