version: 2.1
# orbs:
#   node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      - image: coteh/si-test-deps:0.0.1
    # executor:
    #   name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo apt-get install -y exiftran
            - run: npm install
            - run:
                name: Run tests
                command: npm run test-ci
                environment:
                    MOCHA_FILE: ./junit/simpleimage/test-results.xml
            - store_test_results:
                path: ./junit
workflows:
    build-and-test:
      jobs:
        - build-and-test